[package]
name = "azcon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "azcon"
path = "src/main.rs"
edition = "2021"


[dependencies]
futures = { version = "0.3.*" }